### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by edalford11** [atljeremy/JFMinimalNotifications#7] opened 2015-01-20 20:00 UTC
Tested on iPhone 6 and 6 plus and very buggy. Notification gets on the screen and immediately disappears then reappears again then never goes away even with tap event dismissal attached. Notification banner layout is not robust. Doesn't span according to the screen width of different devices.

**Comment by atljeremy** [comment] 2015-01-20 20:35
Can you be a little more clear regarding your applications view architecture and where you are trying to present the notifications from? I've tested them on all different devices, iPhone 4, iPhone 5, iPhone 6, iPhone 6+, iPad 3, etc. and the notifications layout properly for all. If you can provide me with a sample application showing what you are seeing I can look into it.

**Comment by atljeremy** [comment] 2015-01-20 20:38
Also, please take a look at this issue which sounds similar to what you are saying you are seeing. https://github.com/atljeremy/JFMinimalNotifications/issues/6

**Comment by atljeremy** [comment] 2015-01-21 17:04
@edalford11 Any update on this? Have you looked at issue https://github.com/atljeremy/JFMinimalNotifications/issues/6? Is this the same issue you are having? Can you please describe the view hierarchy of your application and where you are trying to present the notification from? Alternatively, can you provide a sample application that reproduces the issues you've mentioned?

I am not able to reproduce these issues so I can not move forward with any solutions until I here back from you.

**Comment by atljeremy** [comment] 2015-01-23 17:13
Closing this issue since there has not been any activity from the poster since posting the issue and I can not reproduce the issue. If someone would like to reopen this issue at a later date that's perfectly acceptable, however, I do ask that you provide an example project showing the issues. This will allow me to properly investigate and address any possible issues.

**Closed by atljeremy** 2015-01-23 17:13 UTC
