### ISSUE TITLE
Crashes in [JFMinimalNotification configureInitialNotificationConstraintsForTopPresentation:]

### ISSUE THREAD

**Issue by billburgess** [atljeremy/JFMinimalNotifications#10] opened 2015-04-15 13:23 UTC
I keep getting a few crashes showing up in my app with some errors.

Fatal Exception: NSInternalInconsistencyException
NSDictionaryOfVariableBindings failed because either one of the values is nil, or there's something wrong with the way the macro is being invoked. Cannot assign value nil for key "superview". Keys:( superview, notification )

It is coming from the JFMinimalNotifications.m line 239. I'm guessing the superview is nil, but not exactly sure how to recreate it as the number of crashes are pretty small. Opening this issue to see if anyone else is having the same issue or if I'm doing something wrong. My implementation is identical to the example, nothing too flashy. But this has crashed my app a few times and would like to patch it up if possible.
![screen shot 2015-04-15 at 8 22 33 am](https://cloud.githubusercontent.com/assets/644761/7159553/a06c0536-e348-11e4-89f6-5dc1367b4518.png)

**Comment by atljeremy** [comment] 2015-04-15 13:30
Thanks for letting me know. I've not seen this before but I'll see if I can dig into it and try to determine exactly what's causing this. Can you provide me with a sample of the code in your project where you are using JFMinimalNotification that is cause this crash? I just want to make sure I can reproduce this and knowing exactly how you're using it would help.

**Comment by billburgess** [comment] 2015-04-15 13:32
- (void)showToastWithMessage:(NSString *)message {
    if (notification) {
        [notification dismiss];
        [notification removeFromSuperview];
        notification = nil;
    }
    
    notification = [JFMinimalNotification notificationWithStyle:JFMinimalNotificationStyleError
                                                          title:NSLocalizedString(@"Refresh Error", @"Refresh Error")
                                                       subTitle:message
                                                 dismissalDelay:10.0];
    
    /**
     * Set the desired font for the title and sub-title labels
     * Default is System Normal
     */
    UIFont* titleFont = [UIFont systemFontOfSize:22.0];
    [notification setTitleFont:titleFont];
    UIFont* subTitleFont = [UIFont systemFontOfSize:16.0];
    [notification setSubTitleFont:subTitleFont];
    
    /**
     * Add the notification to a view
     */
    [self.view addSubview:notification];
    
    // show
    [self performSelector:@selector(showNotification) withObject:nil afterDelay:0.1];
}

- (void)showNotification {
    [notification show];
}

**Comment by atljeremy** [comment] 2015-04-15 13:34
Great thanks. I'll let you know what I find.

**Comment by billburgess** [comment] 2015-04-15 13:35
Thanks! Sorry for the formatting.

**Comment by atljeremy** [comment] 2015-04-17 19:39
@billburgess Can you please confirm that all calls to `showToastWithMessage:` are called from the main thread? I've not been able to reproduce this issue and the only thing that is coming to mind is that you are trying to call this method from a background thread. Let me know if that is or is not the case.

**Comment by billburgess** [comment] 2015-04-17 20:25
I'm not explicitly calling it from a background thread, but not calling it from main either. I only call when my API delegate is called with an error. I've wrapped the call in a main thread to protect it for future issues. I'll let you know how it goes. I've been unable to reproduce it myself, but some users are falling victim somehow.

**Comment by atljeremy** [comment] 2015-04-17 22:44
OK, I highly suspect there were multiple calls being made to `showToastWithMessage:` from an asynchronous thread and that is the root cause of this issue. For now, since neither of us can reproduce this issue, I'm marking this as resolved. If you, or anyone else, gets more info on this or can provide me with steps to reproduce it I'll reopen the issue.

**Closed by atljeremy** 2015-04-17 22:44 UTC
Labels: investigate

**Comment by atljeremy** [comment] 2015-04-17 22:55
Also, I've added a few new updates to address other issues as well as a small update to possibly reduce the risk of this issue happening in https://github.com/atljeremy/JFMinimalNotifications/releases/tag/0.0.3 which is also available via cocoapods https://cocoapods.org/pods/JFMinimalNotifications.

**Comment by PasqualePuzio** [comment] 2015-04-20 21:22
Hi guys, I'm struggling with the same issue. Although I don't manage to reproduce the issue, one of my apps is crashing from time to time because of it. Any idea of what may be the cause? Thanks

![screen shot 2015-04-20 at 23 20 18](https://cloud.githubusercontent.com/assets/7646303/7240775/e01ba5e6-e7b3-11e4-8933-973884aab370.png)

**Comment by atljeremy** [comment] 2015-04-20 21:24
@PasqualePuzio Can you please confirm the thread in which this stack trace was captured? Also, please make sure that there are no calls to `show` or `dismiss` happening async threads.

**Comment by PasqualePuzio** [comment] 2015-04-20 21:42
The crash is occurring in the main thread.

**Comment by atljeremy** [comment] 2015-04-20 21:53
@PasqualePuzio OK, can you please confirm that all calls to `show` and `dismiss` are happening on the main thread. It could still have been that an async thread called `dismiss` right before the main thread called `show`, or something like that.

Any other info that this stack trace? I've not been able to reproduce this myself, nor has anyone else who's reported it. Without having some sort of an idea on how to reproduce this it will be nearly impossible to address.

**Comment by PasqualePuzio** [comment] 2015-04-20 23:45
@atljeremy I confirm that calls to show and dismiss are happening on the main thread.
To give you more info, show and dismiss are sometimes called upon receiving notifications from NSNotificationCenter or calling performSelectorAfterDelay. However, both of them are being executed in the same thread, that is the main thread.

I would like to give you more info but as I said I'm not even able to reproduce the issue myself. What I know for sure is that this issue is affecting many users.

Thanks

**Comment by atljeremy** [comment] 2015-04-21 00:27
@PasqualePuzio Help me understand the effected users...

% of total user base effected:
# of unique effected users:
# of times this crash has occurred:
Effected devices:
Effected OS versions:

Also, can you send me a complete stack trace? Maybe looking through the additional threads will help shed some light on this issue.

**Comment by PasqualePuzio** [comment] 2015-04-21 08:48
hi @atljeremy 

Percentage of total user base effected: around 20%
Number of times this crash has occurred: 30
Effected devices: both iPad and iPhone
Effected OS versions: iOS 8

and here is the list of threads running at the moment of the crash

![jfminimalnotification crash](https://cloud.githubusercontent.com/assets/7646303/7248539/d989dddc-e813-11e4-9a23-a514b1c655fe.png)


That's all I have

**Comment by PasqualePuzio** [comment] 2015-04-30 13:07
Hi @atljeremy 

I may have some interesting and useful news. Hopefully they will help you find the reason behind this weird issue.

I noticed that many times I call show in dispatch_after blocks. Here is an example:

self.notification = [JFMinimalNotification notificationWithStyle:style title:title subTitle:subtitle dismissalDelay:2.0];
[self.view addSubview:self.notification];
self.notification.presentFromTop = YES;
double delayInSeconds = 2.0;
dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
        
[self.notification show];

});

**Comment by atljeremy** [comment] 2015-04-30 13:14
@PasqualePuzio That's great news. Let me try to reproduce this using what you've mentioned and I'll get back to you.

**Comment by atljeremy** [comment] 2015-05-01 14:10
@PasqualePuzio @billburgess I've figured this out!

The issue is the `dismissalDelay:` parameter in the convenience constructor. When this is set, it creates an `NSTimer` that takes an `NSInvocation` which calls `dismiss` after the specified `dismissalDelay`. The issue is that if the view that you've added the notification to is deallocated before the timer counts down to 0 and calls `invoke` on the `NSInvocation` this crash will occur because the notifications `superview` is now null. Here's the stack trace I get int the Xcode console when reproducing this.

```
2015-05-01 10:00:48.325 JFMinimalNotification[20297:9693055] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSDictionaryOfVariableBindings failed because either one of the values is nil, or there's something wrong with the way the macro is being invoked.  Cannot assign value nil for key "superview". Keys:(
    superview,
    notification
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107a6bc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000107704bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000107a6bb9d +[NSException raise:format:] + 205
	3   Foundation                          0x00000001072adbc0 _NSDictionaryOfVariableBindings + 844
	4   JFMinimalNotification               0x0000000105c95ccd -[JFMinimalNotification configureInitialNotificationConstraintsForTopPresentation:layoutIfNeeded:] + 557
	5   JFMinimalNotification               0x0000000105c9572d -[JFMinimalNotification dismiss] + 525
	6   CoreFoundation                      0x0000000107961dec __invoking___ + 140
	7   CoreFoundation                      0x0000000107961c42 -[NSInvocation invoke] + 290
	8   Foundation                          0x00000001072b7744 __NSFireTimer + 83
	9   CoreFoundation                      0x00000001079d3174 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	10  CoreFoundation                      0x00000001079d2d35 __CFRunLoopDoTimer + 1045
	11  CoreFoundation                      0x0000000107994d3d __CFRunLoopRun + 1901
	12  CoreFoundation                      0x0000000107994366 CFRunLoopRunSpecific + 470
	13  GraphicsServices                    0x000000010a004a3e GSEventRunModal + 161
	14  UIKit                               0x0000000105f92900 UIApplicationMain + 1282
	15  JFMinimalNotification               0x0000000105c8debf main + 111
	16  libdyld.dylib                       0x00000001080b2145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

As you can see, it's the exact same as the stack traces you both provided me with. So, my solution to address this is going to be simply checking if `superview` is `null` and if so return immediately and don't worry about dismissing the notification since the view that it was attached to is now gone (deallocated).

I would also highly encourage you both, and anyone else who may come across this thread alter, to check your app for these types of scenarios so that they do not happen. You'll need to make sure you aren't trying to set dismissalDelay's in the notification constructor which may end up firing after the view the notification is attached to is dismissed/deallocated.

**Comment by atljeremy** [comment] 2015-05-01 14:31
OK, this issue has been addressed in the master branch. I've also added a UI test for this to ensure it doesn't come back.

![jfminimalnotificationuitests_m](https://cloud.githubusercontent.com/assets/1019253/7431513/2851d52e-efed-11e4-8ee7-8abfc15cce59.png)

**Comment by atljeremy** [comment] 2015-05-01 14:38
Just release v0.0.4 which has this fix in it: https://cocoapods.org/pods/JFMinimalNotifications

**Comment by billburgess** [comment] 2015-05-01 15:09
Excellent work! Good catch. I have updates scheduled for my app so I'll pull in the new pod and keep you posted. Thanks for sticking with it.
