### ISSUE TITLE
Discussion: Is throwing an exception too excessive in the case of a missing superview?

### ISSUE THREAD

**Issue by mikemonaco** [atljeremy/JFMinimalNotifications#28] opened 2016-01-18 22:40 UTC
Currently, if you try to show a notification that has not been added to a superview, it will throw an exception.

I've seen cases where the application's keyWindow may be nil for a period of time, perhaps during a transition. [notificationView show] popped up a handful of times in our crash logs.

I would sooner expect nothing to show if keyWindow was nil.

```
[[UIApplication sharedApplication].keyWindow addSubview:notificationView];
[notificationView show]; // exception is thrown if keyWindow is nil
```

Perhaps it would be appropriate to fail more gracefully? (NSLog/Warning/Etc.)

**Comment by atljeremy** [comment] 2016-01-18 23:40
@mikemonaco Thanks for the feedback. This was originally by design so that if you were attempting to show a notification without a superview, you wouldn't just end up with nothing happening. You would get the instant feedback (via exception) that there was an internal inconsistency (missing superview).

I think maybe a good compromise would be to add a delegate call of something like `notificationAttemptedToCallShowWithoutSuperview:(JFMinimalNotification*)notification` with no other logic after that. That way, your delegate can decide what to do in the event you call `show` without a `superview`. If you want to log an error, go for it. If you want to throw an exception while in debug mode and log an error in production, go for it. If you want to ignore it all together, go for it.

What do you think?

**Comment by mikemonaco** [comment] 2016-01-20 04:07
Hmm, doesn't seem like enough to justify creating a delegate protocol. If the worry is people will forget to set a superview, perhaps something like this?

```
- (void)show __attribute__((deprecated("use showInView: instead.")));
- (BOOL)showInView:(UIView *)view;
```

Also just to note, my issue I had with the keyWindow being nil may have been caused by not running on the main thread. Im not 100% sure but I'll do some testing. I know other frameworks such as MBProgressHud (which is in some ways very similar to the use case here) will assert you are running on the main thread...

```
NSAssert([NSThread isMainThread], @"MBProgressHUD needs to be accessed on the main thread.");
```

And as I type this perhaps an assertion is a good compromise with handling the nil superview. I think this is better than the my showInView suggestion above:

```
NSAssert(self.superview != nil, @"JFMinimalNotification must have a superview before calling show");
```

AFAIK, Xcode disables assertions in release builds so this would avoid exception crashes in production apps.

Cheers!

**Comment by atljeremy** [comment] 2016-01-20 14:07
Just to be clear, I wouldn't be creating a delegate protocol for this, just adding a new method definition to the existing `JFMinimalNotificationDelegate` protocol. However, if that's not something of interest/value, then we can certainly explore other options.

My concern isn't for people calling show without adding the notification to a view. My worry was for something like what you created this issue for. That being, you create a notification instance, you add it to a view (in your case the keyWindow) but by the time you actually call `show` on the notification instance the notification's superview (again, in your case the keyWindow) is nil. In this case, nothing would happen and there wouldn't be any feedback to the developer or the user that something is wrong. If there is supposed to be a notification being displayed to the user, that's visual feedback to the user of what's happening, and is probably pretty important. To just not do anything seems like a really bad UX from an end user standpoint.

Regarding the assertion, I really see no difference in using an `NSException` or an `NSAssert` in this use case. In fact, if you look at the code, it's essentially doing exactly what an `NSAssert` would be doing. It first checks to see if there is a `superview` and if not, it throws the exception so that you can get the backtrace and can see what went wrong so it can be diagnosed and corrected. My concern with allowing an `NSAssert` (that can be disabled in prod builds) or some other form of simple error logging is that you are only masking a potentially serious issue. If you add a notification instance to a view and call show on it, but at that time the notifications superview is nil, you have a memory issue in your application that needs to be addressed. Not addressing the root cause could lead to further memory problems and your app would likely crash anyways. Additionally, a notification is meant to provide the end user with visual feedback. If you are going to initialize and configure an instance of the notification only to have it never be displayed to the end user, what's the point? Why would you be OK with this happening? Maybe it's better than the app crashing, sure. But I still believe that if this is happening then you have bigger issues to consider in your app that should probably be addressed which will result in the notification being shown and not an exception being thrown.

If you feel strongly about the `NSAssert` over throwing the `NSException`, I'm always open to contributions to the library. You are more than welcome to submit a PR with the changes you'd like to propose and we can talk through them and see about getting them added to the library.

Again, thanks for the great feedback and discussion!

**Comment by atljeremy** [comment] 2016-02-11 16:01
I haven't received any more feedback on this issue fore 22 days. Closing this issue until there is more feedback to work with.

**Closed by atljeremy** 2016-02-11 16:01 UTC
Labels: awaiting feedback
